_target_: src.ViTmodule.ViTModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.ViTNet.SimpleViT
  image_size: 32
  patch_size: 2
  num_classes: 10
  dim: 64
  depth: 3
  heads: 6
  mlp_dim: 128 

# compile model for faster training with pytorch 2.0
compile: false